[config]
# Mandatory config section for matugen

[templates.synapse]
input_path = './templates/synapse-colors.json.example'
output_path = '~/.config/Synapse/src/user_data/colors.json'

[templates.hyprland_colors_lua]
input_path = "./templates/colors.lua.template"
output_path = "~/.config/hypr/modules/colors.lua"

[templates.neovim]
input_path = "./templates/nvim-colors.json"
output_path = "~/.config/nvim/colors/nvim-colors.json"
post_hook = "pkill -SIGUSR1 nvim"