return {
    {
        "zaldih/themery.nvim",
        lazy = false,
        config = function()
            require("themery").setup({
                themes = { "onedark", "catppuccin", "gruvbox-material", "kanagawa-paper", "gruvbox", "base46-matugen" },
            })

            local keymap = vim.keymap.set
            keymap("n", "<leader>tt", "<Cmd>Themery<CR>", { desc = "Switch colorscheme" })
        end,
    },
    {
        "navarasu/onedark.nvim",
        priority = 1000,
        config = function()
            require("onedark").setup({
                style = "darker",
                -- toggle theme style ---
                toggle_style_key = "<leader>p", -- keybind to toggle theme style. Leave it nil to disable it, or set it to a string, for example "<leader>ts"
                toggle_style_list = { "darker", "deep", "warmer" }, -- List of styles to toggle between

                lualine = {
                    transparent = false, -- lualine center bar transparency
                },
                highlights = {
                    AlphaHeader = { fg = "#61AFEF", bold = true },
                },
            })

            -- vim.cmd("colorscheme onedark")
        end,
    },
    {
        "catppuccin/nvim",
        name = "catppuccin",
        priority = 1000,
        config = function()
            -- vim.cmd("colorscheme catppuccin")
        end,
    },
    {
        "ellisonleao/gruvbox.nvim",
        priority = 1000,
        config = function()
            -- vim.cmd("colorscheme gruvbox")
        end,
    },
    {
        "sainnhe/gruvbox-material",
        priority = 1000,
        config = function()
            -- vim.cmd("colorscheme gruvbox-material")
        end,
    },
    {
        "thesimonho/kanagawa-paper.nvim",
        priority = 1000,
        config = function()
            -- vim.cmd("colorscheme kanagawa-paper")
        end,
    },
    {
        "Senal-D-A-Gunaratna/matugen.nvim",
        lazy = false,
        priority = 1000,
        opts = {
            load_theme = true, -- set this to false to stop the theme from loading

            -- Path to the JSON file generated by matugen
            palette_path = "~/.config/nvim/colors/nvim-colors.json",
        },
    }
}
