-- Synapse keybindings
--
-- Synapse popup binds (Super+D, Super+V, Super+A, Super+M, Super+N, Super+W,
-- Super+B, Super+Escape, Alt+F9, etc.) are NOT listed here to avoid conflicts.
-- They're generated by Quickshell (KeybindService.qml) from keybind-defaults.json
-- + user overrides, and loaded via require("modules/synapse-keybinds") in
-- hyprland.lua. The Synapse installer will warn if any overlap is detected.

-- ── App launchers ─────────────────────────────────────────────────────────────
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"))
hl.bind("SUPER + E",      hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind("SUPER + B",      hl.dsp.exec_cmd("zen-browser"))

-- ── Window management ─────────────────────────────────────────────────────────
hl.bind("SUPER + W",          hl.dsp.window.close())
hl.bind("SUPER + F",          hl.dsp.window.fullscreen({mode = "fullscreen"}))
hl.bind("SUPER + M",          hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind("SUPER + T",          hl.dsp.window.float({ action = "toggle" }))

-- ── Focus navigation ──────────────────────────────────────────────────────────
hl.bind("SUPER + left",  hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up",    hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down",  hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + H",     hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + J",     hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + K",     hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + L",     hl.dsp.focus({ direction = "right" }))

-- ── Window movement ───────────────────────────────────────────────────────────
hl.bind("SUPER + SHIFT + left",  hl.dsp.window.swap({ direction = "left" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.swap({ direction = "right" }))
hl.bind("SUPER + SHIFT + up",    hl.dsp.window.swap({ direction = "up" }))
hl.bind("SUPER + SHIFT + down",  hl.dsp.window.swap({ direction = "down" }))

-- ── Window resize ─────────────────────────────────────────────────────────────
hl.bind("SUPER + CTRL + left",  hl.dsp.exec_raw("resizeactive -100 0"), { repeating = true })
hl.bind("SUPER + CTRL + right", hl.dsp.exec_raw("resizeactive 100 0"),  { repeating = true })
hl.bind("SUPER + CTRL + up",    hl.dsp.exec_raw("resizeactive 0 -100"), { repeating = true })
hl.bind("SUPER + CTRL + down",  hl.dsp.exec_raw("resizeactive 0 100"),  { repeating = true })

-- ── Workspaces ────────────────────────────────────────────────────────────────
for i = 1, 9 do
    hl.bind("SUPER + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind("SUPER + 0",         hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Mouse workspace cycling
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse_up",   hl.dsp.focus({ workspace = "e+1" }))

-- Mouse window control
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ── Plugins ───────────────────────────────────────────────────────────────────
hl.bind("SUPER + G", function()
    hl.plugin.scrolloverview.overview("toggle")
end)
hl.define_submap("scrolloverview", function()
	hl.bind("left", hl.plugin.scrolloverview.navigate("left"))
	hl.bind("right", hl.plugin.scrolloverview.navigate("right"))
	hl.bind("up", hl.plugin.scrolloverview.navigate("up"))
	hl.bind("down", hl.plugin.scrolloverview.navigate("down"))
	hl.bind("return", hl.plugin.scrolloverview.overview("select"))
	hl.bind("escape", hl.plugin.scrolloverview.overview("off"))
	hl.bind("mouse:272", function()
		-- Select the clicked window, or just the workspace if no window was clicked, then close the overview. This is the default behaviour if submap is not defined.
		hl.plugin.scrolloverview.overview("select")
		hl.plugin.scrolloverview.window("select")
		hl.plugin.scrolloverview.overview("off")
	end, { mouse = true })
	hl.bind("mouse:274", hl.plugin.scrolloverview.window("close"), { mouse = true })
end)
-- ── Lock screen ───────────────────────────────────────────────────────────────
hl.bind("SUPER + SHIFT + L",      hl.dsp.exec_cmd("hyprlock"))

-- ── Screenshots (rishot) ──────────────────────────────────────────────────────
-- Print         → region capture or click a window; annotate, then copy/save/upload
-- SHIFT + Print → whole monitor capture
-- Installed by install/steps/02-packages.sh (step 4) into ~/.local/share/rishot;
-- called by full path since ~/.local/bin isn't guaranteed on Hyprland's exec PATH.
local rishot = os.getenv("HOME") .. "/.local/share/rishot/bin/rishot"
hl.bind("Print",         hl.dsp.exec_cmd(rishot))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(rishot .. " monitor"))

-- ── Media controls (work on lock screen) ─────────────────────────────────────
-- Volume/mute keys also reveal the QuickControl OSD popup (quickcontrols-show,
-- see IpcManager.qml). hl.dsp.exec_cmd doesn't run its string through a shell,
-- so chained commands need an explicit bash -c wrapper (same pattern already
-- used elsewhere in this file for multi-step commands).
local QUICK_OSD = "qs ipc call quickcontrols-show reveal"
local function withOSD(cmd)
    return "bash -c '" .. cmd .. " && " .. QUICK_OSD .. "'"
end

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(withOSD("pamixer -i 5")), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(withOSD("pamixer -d 5")), { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd(withOSD("pamixer -t")),   { locked = true })
hl.bind("XF86AudioPlay",        hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext",        hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPrev",        hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- ── Brightness controls (work on lock screen) ────────────────────────────────
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd(withOSD("brightnessctl set +5%")), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(withOSD("brightnessctl set 5%-")), { locked = true, repeating = true })
